# Generated by Django 5.0.7 on 2024-09-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
